### ISSUE TITLE
fail to find the right executable

### ISSUE THREAD

**Issue by mutundis** [bwa-mem2/bwa-mem2#73] opened 2020-07-10 07:43 UTC
Please can you give advice about how to troubleshoot this:

ERROR: fail to find the right executable

which is an error I get when attempting to run the compiled binary bwa-mem2. I get this error on multiple systems including e.g a system with this 8 core CPU:

Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz

Thanks!

**Comment by slw287r** [comment] 2020-07-10 08:48
I encountered exactly the same issue:

```
$ ./bwa-mem2.sse41 
Usage: bwa-mem2 <command> <arguments>
Commands:
  index         create index
  mem           alignment
  version       print version number
$ ./bwa-mem2.avx2
Usage: bwa-mem2 <command> <arguments>
Commands:
  index         create index
  mem           alignment
  version       print version number
$ ./bwa-mem2.avx512bw 

Please verify that both the operating system and the processor support Intel(R) MOVBE, FMA, BMI, LZCNT, AVX2, AVX512DQ, AVX512F, ADX, AVX512CD, AVX512BW, AVX512VL and CLWB instructions.

$ ./bwa-mem2
ERROR: fail to find the right executable
```

I assumed `bwa-mem2` will pick the appropriate `SIMD_` automatically.

Thanks,
Richard

**Comment by yuk12** [comment] 2020-07-11 16:32
@mutundis @slw287r Could you check the permissions on the file, one of the reasons for this error could be execute permission on bwa-mem2 file.
Also, please provide the OS details?

**Comment by slw287r** [comment] 2020-07-12 06:47
I've verified my `SIMD` with the following code snippet:
<details><summary>get simd</summary>

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <limits.h>
#include <assert.h>

#define SIMD_SSE     0x1
#define SIMD_SSE2    0x2
#define SIMD_SSE3    0x4
#define SIMD_SSSE3   0x8
#define SIMD_SSE4_1  0x10
#define SIMD_SSE4_2  0x20
#define SIMD_AVX     0x40
#define SIMD_AVX2    0x80
#define SIMD_AVX512F 0x100
#define SIMD_AVX512BW 0x200

#ifndef _MSC_VER
// adapted from https://github.com/01org/linux-sgx/blob/master/common/inc/internal/linux/cpuid_gnu.h
void __cpuidex(int cpuid[4], int func_id, int subfunc_id)
{
#if defined(__x86_64__)
	__asm__ volatile ("cpuid"
			: "=a" (cpuid[0]), "=b" (cpuid[1]), "=c" (cpuid[2]), "=d" (cpuid[3])
			: "0" (func_id), "2" (subfunc_id));
#else // on 32bit, ebx can NOT be used as PIC code
	__asm__ volatile ("xchgl %%ebx, %1; cpuid; xchgl %%ebx, %1"
			: "=a" (cpuid[0]), "=r" (cpuid[1]), "=c" (cpuid[2]), "=d" (cpuid[3])
			: "0" (func_id), "2" (subfunc_id));
#endif
}
#endif

static int x86_simd(void)
{
	int flag = 0, cpuid[4], max_id;
	__cpuidex(cpuid, 0, 0);
	max_id = cpuid[0];
	if (max_id == 0) return 0;
	__cpuidex(cpuid, 1, 0);
	if (cpuid[3]>>25&1) flag |= SIMD_SSE;
	if (cpuid[3]>>26&1) flag |= SIMD_SSE2;
	if (cpuid[2]>>0 &1) flag |= SIMD_SSE3;
	if (cpuid[2]>>9 &1) flag |= SIMD_SSSE3;
	if (cpuid[2]>>19&1) flag |= SIMD_SSE4_1;
	if (cpuid[2]>>20&1) flag |= SIMD_SSE4_2;
	if (cpuid[2]>>28&1) flag |= SIMD_AVX;
	if (max_id >= 7) {
		__cpuidex(cpuid, 7, 0);
		if (cpuid[1]>>5 &1) flag |= SIMD_AVX2;
		if (cpuid[1]>>16&1) flag |= SIMD_AVX512F;
		if (cpuid[1]>>30&1) flag |= SIMD_AVX512BW;
	}
	return flag;
}

int main()
{
	int simd = x86_simd();
	if (simd & SIMD_AVX512BW) puts("bwa-mem2.avx512bw");
	if (simd & SIMD_AVX512F) puts("bwa-mem2.avx512f");
	if (simd & SIMD_AVX2) puts("bwa-mem2.avx2");
	if (simd & SIMD_AVX) puts("bwa-mem2.avx");
	if (simd & SIMD_SSE4_2) puts("bwa-mem2.sse42");
	if (simd & SIMD_SSE4_1) puts("bwa-mem2.sse41");
	if (simd & SIMD_SSE2) puts("bwa-mem2.sse2");
	if (simd & SIMD_SSE) puts("bwa-mem2.sse");
	return 0;
}
```
</details>

and it supports the followings executables 
```
bwa-mem2.avx
bwa-mem2.sse42
bwa-mem2.sse41
bwa-mem2.sse2
bwa-mem2.sse
```

I got the following executables from the release tar w/o `bwa-mem2.avx`
```
-rwxr-xr-x. 1 foo bar   29848 Jul  9 00:52 bwa-mem2
-rwxr-xr-x. 1 foo bar 1482808 Jul  9 00:51 bwa-mem2.avx2
-rwxr-xr-x. 1 foo bar 1539540 Jul  9 00:52 bwa-mem2.avx512bw
-rwxr-xr-x. 1 foo bar 1464353 Jul  9 00:51 bwa-mem2.sse41
```
After making a symbolic link of `bwa-mem2.avx2` to `bwa-mem2.avx`, `bwa-mem2` works as expected.

Thanks,
Richard

**Comment by philippbayer** [comment] 2020-07-13 06:17
Found this thread via google as I had the same error, @slw287r's solution works fine for me.

**Comment by keiranmraine** [comment] 2020-07-13 13:50
Additional for this, slightly legacy hardware `AMD Opteron(tm) Processor 6378` supporting `sse4_1` & `sse4_2` gives:

```
ERROR: fail to find the right executable
```

(we have new intel also, but need to use the old stuff too ideally)

**Comment by keiranmraine** [comment] 2020-07-14 10:27
I can confirm that the above get_smid code works correctly for:

*  AMD Opteron(tm) Processor 6174
   *  bwa-mem2.sse2, bwa-mem2.sse
*  AMD Opteron(tm) Processor 6272
   *  bwa-mem2.avx, bwa-mem2.sse42, bwa-mem2.sse41, bwa-mem2.sse2, bwa-mem2.sse
*  AMD Opteron(tm) Processor 6378
   *  bwa-mem2.avx, bwa-mem2.sse42, bwa-mem2.sse41, bwa-mem2.sse2, bwa-mem2.sse

**Comment by mp15** [comment] 2020-07-14 10:53
It looks like `make multi` produces only bwa-mem2.sse41, bwa-mem2.avx2 and bwa-mem2.avx512bw. Whereas as @keiranmraine has pointed out to me https://github.com/bwa-mem2/bwa-mem2/blob/96b21e44b9a4829beb29a15a57c359d1fe9eaec1/src/runsimd.cpp#L181-L188 supports a lot more systems than that.

**Comment by keiranmraine** [comment] 2020-07-14 10:56
Looking at the code there are only 4 modes:

https://github.com/bwa-mem2/bwa-mem2/blob/771c7692aeb857d5b9241a08bbd68f2c6be01811/src/main.cpp#L78-L89

I think we could modify that block to point ("not a C programmer"):

*  `SIMD_AVX512F` -> `.avx2`
*  `SIMD_AVX`  -> `.sse41`
*  `SIMD_SSE4_2` -> `.sse41`
*  `SMID_SSE2` -> `null`
*  `SMID_SSE` -> `null`

https://github.com/bwa-mem2/bwa-mem2/blob/771c7692aeb857d5b9241a08bbd68f2c6be01811/src/runsimd.cpp#L181-L188

**Comment by sanchit-misra** [comment] 2020-07-14 12:58
@keiranmraine and @mp15, your observations are correct. Let me fix this.

**Comment by keiranmraine** [comment] 2020-07-16 12:28
@sanchit-misra happy to do early testing, have easy access to :

* Intel Xeon Gold 6242 (sse/sse2/sse4_1/sse4_2/avx/avx2/avx512f/avx512bw)
* AMD Opteron 6378 (sse/sse2/sse4_1/sse4_2)
* AMD Opteron 6272 (sse/sse2/sse4_1/sse4_2)
* AMD Opteron 6174 (sse/sse2) - heading to bin v.soon

I realise the AMD are of less interest, but they will help confirm the code path down to sse2 is functional.

**Comment by sanchit-misra** [comment] 2020-07-21 13:38
@keiranmraine: As per the code, any machine that supports sse41 should not see this error. I have added some extra logging to the code. Could you please checkout the branch: "fail_to_find_executable" and try running bwa-mem2 on the machines on which this fails and let me know the output?

For example, on the machines I have access to this succeeds:
**Intel Xeon E5-2699 v4** (supports AVX2)
$ ./bwa-mem2
Looking to launch executable "...../bwa-mem2/fail_to_find_executable/./bwa-mem2.avx2", simd = .avx2
stat(prefix, &st) = 0
(st.st_mode & S_IXUSR) = 64
Launching executable "/data/nfs_home/smisra/bwa-mem2/fail_to_find_executable/./bwa-mem2.avx2"
Usage: bwa-mem2 <command> <arguments>
Commands:
  index         create index
  mem           alignment
  version       print version number

**Intel Platinum 8280** (supports AVX512)
$ ./bwa-mem2
Looking to launch executable "/nfs_home/smisra/bwa-mem2/fail_to_find_executable/./bwa-mem2.avx512bw", simd = .avx512bw
stat(prefix, &st) = 0
(st.st_mode & S_IXUSR) = 64
Launching executable "/nfs_home/smisra/bwa-mem2/fail_to_find_executable/./bwa-mem2.avx512bw"
Usage: bwa-mem2 <command> <arguments>
Commands:
  index         create index
  mem           alignment
  version       print version number

**Comment by cgjosephlee** [comment] 2020-07-23 09:07
Hi @sanchit-misra ,
I'm using a machine equipped with a `AMD Opteron(tm) Processor 6386 SE`, which supports SSE4.1 only.
```
make multi
./bwa-mem2
Looking to launch executable "/home/hhl/local/bwa-mem2/./bwa-mem2.avx", simd = .avx
stat(prefix, &st) = -1
Can not run executable: /home/hhl/local/bwa-mem2/./bwa-mem2.avx
Looking to launch executable "/home/hhl/local/bwa-mem2/./bwa-mem2.avx.sse42", simd = .sse42
stat(prefix, &st) = -1
Can not run executable: /home/hhl/local/bwa-mem2/./bwa-mem2.avx.sse42
Looking to launch executable "/home/hhl/local/bwa-mem2/./bwa-mem2.avx.sse42.sse41", simd = .sse41
stat(prefix, &st) = -1
Can not run executable: /home/hhl/local/bwa-mem2/./bwa-mem2.avx.sse42.sse41
Looking to launch executable "/home/hhl/local/bwa-mem2/./bwa-mem2.avx.sse42.sse41.sse2", simd = .sse2
stat(prefix, &st) = -1
Can not run executable: /home/hhl/local/bwa-mem2/./bwa-mem2.avx.sse42.sse41.sse2
Looking to launch executable "/home/hhl/local/bwa-mem2/./bwa-mem2.avx.sse42.sse41.sse2.sse", simd = .sse
stat(prefix, &st) = -1
Can not run executable: /home/hhl/local/bwa-mem2/./bwa-mem2.avx.sse42.sse41.sse2.sse
ERROR: fail to find the right executable
```

**Comment by sanchit-misra** [comment] 2020-07-23 09:29
Thanks @cgjosephlee for confirming what @EdHarry suggested. I have fixed it using his solution. Can you try now?

**Comment by cgjosephlee** [comment] 2020-07-23 09:42
It works! hooray!
```
$ ./bwa-mem2
Looking to launch executable "/home/hhl/local/bwa-mem2/./bwa-mem2.avx", simd = .avx
stat(prefix, &st) = -1
Can not run executable: /home/hhl/local/bwa-mem2/./bwa-mem2.avx
Looking to launch executable "/home/hhl/local/bwa-mem2/./bwa-mem2.sse42", simd = .sse42
stat(prefix, &st) = -1
Can not run executable: /home/hhl/local/bwa-mem2/./bwa-mem2.sse42
Looking to launch executable "/home/hhl/local/bwa-mem2/./bwa-mem2.sse41", simd = .sse41
stat(prefix, &st) = 0
(st.st_mode & S_IXUSR) = 64
Launching executable "/home/hhl/local/bwa-mem2/./bwa-mem2.sse41"
Usage: bwa-mem2 <command> <arguments>
Commands:
  index         create index
  mem           alignment
  version       print version number
```

**Comment by sanchit-misra** [comment] 2020-07-23 14:08
Merged the fail_to_find_executable to master branch.

**Closed by sanchit-misra** 2020-07-23 14:08 UTC

**Comment by marrip** [comment] 2024-07-23 09:56
hey,

I am using the docker container image `quay.io/biocontainers/bwa-mem2:2.2.1--he513fc3_0 bwa-mem2`, starting it with `bash`:

```bash
sudo docker run -it --rm quay.io/biocontainers/bwa-mem2:2.2.1--he513fc3_0 bash
```

I get `ERROR: fail to find the right executable` when I call `bwa-mem2`. Any idea why this is? I considered the linking but the file already exists.
