### ISSUE TITLE
Size of index files

### ISSUE THREAD

**Issue by dparks1134** [bwa-mem2/bwa-mem2#78] opened 2020-07-13 19:03 UTC
Hi,

Thank you for putting together bwa-mem2. I am looking to use it on an index built across a couple thousand bacterial genomes which results in an input file with 6.9 gigabases. The resulting bwa-mem2 index is ~180 GB across the different output files (80 GB for `<prefix>.bwt.2bit.64`; 90 GB for `<prefix>.bwt.8bit.32`; 13 GB for `<prefix>.0123`). Is this expected? It is a dramatic increase from bwa-mem which requires ~11 GB.

Perhaps not surprisingly, this also means bwa-mem2 (~6 min) is slower than bwa-mem (~4.5 min) when mapping a moderately sized input file (say, 10 million paired reads). This appears to be the result of the time required to read the bwa-mem2 index before doing the mapping. Bwa-mem2 also required ~100 GB of RAM compared to the ~13 GB of bwa-mem. 

Is this use cases outside the scope of bwa-mem2 or is there interest in trying to optimize this scenario? I would be happy to provide assistance in this regard.

Thanks,
Donovan

**Comment by sanchit-misra** [comment] 2020-07-14 12:53
Hi @dparks1134, thank you for your message. The size of index you observed is expected for an input of size 6.9 Gigabases. In general, the <prefix>.bwt.8bit.32 file consumes about 14*N GB of space where N is the size of the input in Gigabases. For example, for 6.9 Gigabases, it should be of size 96.6 GB. You only need one of the two index files for execution. If your machine supports AVX2, it would use ".8bit.32" file, else it would use ".2bit.64" file. 
The reason for the dramatic increase is that we use uncompressed suffix array compared to bwa-mem that uses compressed one. This is a classic case of trading speed for memory. You can read more about it here: https://arxiv.org/abs/1907.12931

BWA-MEM2 was written to support use cases in which BWA-MEM is required to run for hours, if not days. To us, those are the use cases where the 2x speedup has a significant impact. We would love to understand more about your use case to see if we can support it in any way.
Having said that, in the short term, we do plan to use a gz compressed file instead of the regular one for the index which should help a bit. Also, we have considered compressing the suffix array a bit - not to the extent BWA-MEM does - to see if we can still get good performance.

**Comment by keiranmraine** [comment] 2020-07-14 17:06
I'd like to express support of compression of the index files to reduce I/O overhead.  In testing my experience was this phase of startup was heavily disk bound even on a lustre filesystem.

**Comment by dparks1134** [comment] 2020-07-14 19:27
Hi @sanchit-misra, thank you for the quick response. My use case is mapping reads to indices such as the one mentioned above (i.e. in the 5 to 10 Gbase range). The potential speed up of bwa-mem2 is of interest since I map to several such indices and do this for hundreds of samples so all together am looking at something like 5 min/index * 10 indices * 100 samples = 3.5 days. This computation needs to be repeat each sequencing run (say weekly) so optimization is a concern. I'm looking to do this computation on cloud infrastructure, so there is the additional time and financial considerations related to indices being transferred to temporary VMs, the required memory specs for these VMs, and storage costs related to the indices.

A compressed index file, especially if it could be tuned for specific use cases, would be a huge help since this would potentially let me find the sweet spot for the different dimensions I'm trying to optimize.

**Comment by rhpvorderman** [comment] 2020-07-21 11:19
I'd like to add that having a compressed file *on disk* does not mean you have to keep it compressed *in memory* ? Right? And actually with such big files I/O speed **will** be the bottleneck for reading in the files. As decompression is faster than disk troughput in most cases.

So compressing the suffix array on disk and using it decompressed in memory seems like the sane default to me if you prefer speed. Is that possible?

**Comment by sanchit-misra** [comment] 2020-07-21 13:40
@rhpvorderman Yes, that is what we are doing.

**Comment by rhpvorderman** [comment] 2020-07-21 14:42
Great. thanks!

**Comment by rhpvorderman** [comment] 2020-07-29 09:27
I tested the compressibility of the indexes using [igzip](https://github.com/intel/isa-l). This uses the default level of 2.

- 2bit.64: 36G -> 28G
- 8bit.32: 42G -> 29G

This saves about 20G on a total of 85G of index files. However since the compressability of these files is not so great I think it will take significantly longer to unpack the indexes compared to just loading the uncompressed indexes from disk.

Regardless the compute and wall clock time needed to unpack the indexes is insignificant compared ~ to the time needed for alignment anyway, while the compression improves the disk size usage quite substantially.

**Comment by keiranmraine** [comment] 2020-07-29 13:26
Although I agree compression doesn't improved overall performance *in an ideal world*, we do have to consider the impact of where the data may be read from within real environments.

I compressed with igzip at each of the available levels, both level 1 & 2 resulted in a 28GB file (<1% difference in size, GRCh38 2bit.64, originally 36GB as @rhpvorderman example).

I can read the same data from /tmp at ~3-4x faster than for our high performance lustre:

1. data read from /tmp for ~read speed (second read shown)
2. decompression data rate

```
# first show raw read speed of original data
$ cat /tmp/genome.fa.bwt.2bit.64 | pv -at > /dev/null
0:00:16 [2.17GiB/s]
# igzip -1
$ cat /tmp/igzip-1 | pv -at > /dev/null
0:00:11 [2.33GiB/s]
$ isa-l-master/programs/igzip -dc /tmp/igzip-1 | pv -at > /dev/null
0:01:04 [ 568MiB/s]
# igzip -2
$ cat /tmp/igzip-2 | pv -at > /dev/null
0:00:11 [2.38GiB/s]
$ isa-l-master/programs/igzip -dc /tmp/igzip-2 | pv -at > /dev/null
0:00:59 [ 614MiB/s]
```

The problem is that the above doesn't actually reflect reality for many users.  Multi use clusters mean the reference being on fast /tmp is rarely the case, we use lustre which is pretty fast, but its ~25% of the read speed of /tmp.  This means that between disk I/O limits, network congestion etc needing to get less data to the "worker" results in decompression being almost completely negated:

```
# lustre, unstriped
$ cat genome.fa.bwt.2bit.64 | pv -at > /dev/null
0:01:26 [ 425MiB/s]
$ cat igzip-2 | pv -at > /dev/null
0:01:08 [ 410MiB/s]
$ ./isa-l-master/programs/igzip -dc igzip-2 | pv -at > /dev/null
0:01:30 [ 408MiB/s]
```

As you can see it takes 4 seconds longer, but we have transferred ~33% less data.  Thinking of the whole ecosystem is important in these cases.

In a perfect world you'd have the reference on the workers, but when you support 20-30 different species and genome builds that becomes problematic.

**Comment by sanchit-misra** [comment] 2020-08-01 11:52
After initially experimenting with compression and realizing that the compression factor is very low and compression/decompression time is very high, we have paused our efforts on that idea for now.
We are working on trying to reduce the size of FM-index and Suffix array while maintaining a small (< 5%) penalty on performance.

**Comment by sanchit-misra** [comment] 2020-08-06 11:33
Update: we have been successful in compressing the suffix array by 4x with only 2-3% increase in time. We are looking to see if we can compress it by 8x and also making sure that part of the code is running efficiently. If it is compressed by 8x, the index will come down from 42GB to 16 GB. 
We are also looking to reduce the size of FM-index from 12 GB to 6GB to bring down the total index size to 10GB.

**Comment by zamaudio** [comment] 2020-08-27 00:10
I've been trying to follow this thread, but I am still confused: Is the goal of this issue to reduce the memory footprint of bwa-mem2, or just the size of the suffix array on disk?  For my use case, I would like to see similar memory usage to original bwa with the rest of the speedups (not including the uncompression of the suffix array).  That way, we could keep running our pipelines without needing to upgrade to more physical memory.

**Comment by yuk12** [comment] 2020-08-28 04:46
@zamaudio  It will reduce the working memory as well as index file size.

**Comment by yuk12** [comment] 2020-09-10 13:24
Hi all, the index size (and memory) footprint has gone down to ~16GB from ~42GB. We see the performance impact of 3%-7% in the non index-IO time -- but, the index reading time is significantly down. Please give it a try (use the latest commit; we will soon release the binaries) and let us know if you face any issues.

**Comment by sanchit-misra** [comment] 2020-09-10 14:00
I also wanted to add that we are working to reduce the index size by another 6GB, to get it down to 10 GB.

**Comment by dparks1134** [comment] 2020-09-10 17:38
Hi. Thank you for the code improvements. I can confirm the index is ~3X smaller for my data. Ultimately, bwa-mem2 is still slower than bwa-mem for my use case (large index file, relatively small number of reads to map) given the time required to read the larger index into memory. Are there any plans to implement a `shm` feature in bwa-mem2 so an index only needs to be loaded once when multiple, independent sequence files need to be mapped to the same index?

**Comment by keiranmraine** [comment] 2020-09-11 08:15
@dparks1134 if your data is that small why do you need bwa-mem2?  We had planned to have our system use vanilla bwa-mem for our targeted data and only use bwa-mem2 for larger datasets.  You could easily switch binary based on input data size.

**Comment by dparks1134** [comment] 2020-09-11 14:39
@keiranmraine We have many large indices and many small, independent data sets so the potential savings of using a faster mapping method are huge.

**Comment by sanchit-misra** [comment] 2020-10-14 11:26
We are done with reducing the index size. The index size on disk is down by 8 times and in memory by 4 times due to moving to only one type of FM-index (2bit.64 instead of 2bit.64 and 8bit.32) and 8x compression of suffix array. For example, for human genome, index size on disk is down to ~10GB from ~80GB and memory footprint is down to ~10GB from ~40GB. There is a substantial reduction in index IO time due to the reduction and hardly any performance impact on read mapping. Due to this change in index structure (in commit #4b59796, 10th October 2020), you will need to rebuild the index.

**Closed** 2020-10-14 11:26 UTC
